config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'landing#index' # ite means url '/'

  # get 'pages/home'

  devise_for :users, :controllers => { :sessions => "users/sessions" ,:registrations => "users/registrations" }
  
  # All Customer Routes
  namespace :customers do
    resources :venues, only: [:index, :show]
    resources :bookings, except: [:new] do
      # collection means we do not need any booking id 
      # while its opposite is member keywork which required id and add it to URL 
      collection do
        get 'venues/:venue_id' => 'bookings#new', as: :new #
        post '/search' , to: 'venues#search_venue', as: :search_venue
      end
    end
  end
  # all venue_Owner routes
  namespace :venue_owner do
    resources :payments  do 
      collection do
         get :get_subscription_payment
         get :update_subscription_payment
      end
    end
    resources :venues 
    resources :bookings do
      member do 
        get :approve
      end
    end

   end
   
  # subscription
  resources :subscription
    get "/subscription/create/:subscription_type" => "subscription#create_subscription"

end



  # get 'landing/index'
# Landing route
  # resources :landing

  #  Customer route
  # login
  # get "/home/login" => "home#login"
  # get "/venue_owner/:id" => "venue_owner#update_subscription"
  
  # post "/saveVO" => "venue_owner#create" 
          # create_booking
  # get "/booking/index" => "booking#index"
  # get  "/booking/new" => "booking#new"
  # post  "/booking" => "booking#create"
  
  # venue route
  
  # post "/venues" => "venues#destroy"

  # get "/venue/" => "venue#index"
  # get "/venue/new" =>  "venue#new"
  # post "venue_create" => "venue#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :User

end

app/controllers/venue_owner/bookings_controller.rb
class VenueOwner::BookingsController < ApplicationController
     layout "landing"
     def index
        venue_ids = Venue.where(user_id: current_user.id)
        # debugger
        @booking = Booking.where(venue_id: venue_ids)
     end

     def destroy    
      debugger
      @booking = Booking.find(params[:id])
        if @booking.destroy!
          BookingMailer.with(booking: @booking, venue:@venue).cancel_booking_email.deliver_now
           redirect_to venue_owner_bookings_path, notice: 'Booking was successfully destroyed.'  
        end
      end

      def approve
         @booking = Booking.find_by_id(params[:id])
         @booking.update(status: "approved")
         if @booking.status == "approved"
             BookingMailer.with(booking: @booking, venue:@venue).approved_booking_email.deliver_now
            redirect_to venue_owner_bookings_path, notice: "Booking successfully approved"
         end
       end

  end

app/controllers/venue_owner/payments_controller.rb
class VenueOwner::PaymentsController < ApplicationController

    protect_from_forgery

    layout "landing"

    def update_subscription_payment          
        current_user.update(payment_status: "paid")
        PaymentMailer.with( venue: @venue, user: current_user).payment_paid_email.deliver_now
        redirect_to venue_owner_venues_path, notice: "payment successfully paid"
    end 

    def get_subscription_payment
        debugger
    current_user.update(subscription: params[:subscription])
        
    end
end

app/controllers/venue_owner/venues_controller.rb
class VenueOwner::VenuesController < ApplicationController

  protect_from_forgery

    layout "landing"
   
  def index
      # @venue = current_user.venues
      # Both Lines are working similar
      @venue = Venue.where(user_id: current_user.id)  
      # PaymentMailer.with( venue: @venue, user: current_user).payment_paid_email.deliver_now
  end

  def new 
      @venue = Venue.new
  end 

  def show
      @venue = Venue.find_by_id(params[:id])
    # debugger
  end

  def edit
        @venue = Venue.find(params[:id])       
  end

  def update
    debugger    
      @venue = Venue.find(params[:id])
      if @venue.update(venue_params)
          redirect_to venue_owner_venues_path, notice: 'Venue was successfully updated.'        
      end
  end

  def create
      @current_user_venues = Venue.where(user_id: current_user.id)
     debugger
    #  Check what is the subscription limit of venue owner and then check if 
    #  he can make a new venue or not.
      if ((current_user.subscription  == 'basic' && @current_user_venues.count  == 2)  || (current_user.subscription  == 'pro' && @current_user_venues.count  == 5))

        redirect_to venue_owner_venues_path, notice: "Please upgrade your subscripton to create new venues" 
      else
        @venue = Venue.new(venue_params)
        @venue.user_id = current_user.id
        @venue.save
        redirect_to venue_owner_venues_path
      end
    end
  
  def destroy
      @venue = Venue.find(params[:id])
      debugger
      @venue.destroy! 
      respond_to do |format|
          format.html { redirect_to venue_owner_venues_url, notice: 'Venue was successfully destroyed.' }
          format.json { head :no_content }
       end
    end

# these are called strong params which is security features which allows
#  only specific keys to be accepted from the web page
  private 
  def venue_params
      params.require(:venue).permit(:name,:address,:venue_type,:price, :contact_no,)
  end
    
end

app/helpers/venue_owner/venues_helper.rb
module VenueOwner::VenuesHelper
end

app/views/venue_owner/payments/get_subscription_payment.erb
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header">
                    <strong>Credit Card</strong>
                    <small>enter your card details</small>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input class="form-control" id="name" type="text" placeholder="Enter your name">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="ccnumber">Credit Card Number</label>
                                <div class="input-group">
                                    <input class="form-control" type="number" placeholder="0000 0000 0000 0000" autocomplete="email">
                                    <div class="input-group-append">
                                        <span class="input-group-text">
                                            <i class="mdi mdi-credit-card"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-4">
                            <label for="ccmonth">Month</label>
                            <select class="form-control" id="ccmonth">
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                                <option>6</option>
                                <option>7</option>
                                <option>8</option>
                                <option>9</option>
                                <option>10</option>
                                <option>11</option>
                                <option>12</option>
                            </select>
                        </div>
                        <div class="form-group col-sm-4">
                            <label for="ccyear">Year</label>
                            <select class="form-control" id="ccyear">
                                <option>2014</option>
                                <option>2015</option>
                                <option>2016</option>
                                <option>2017</option>
                                <option>2018</option>
                                <option>2019</option>
                                <option>2020</option>
                                <option>2021</option>
                                <option>2022</option>
                                <option>2023</option>
                                <option>2024</option>
                                <option>2025</option>
                            </select>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="cvv">CVV/CVC</label>
                                <input class="form-control" id="cvv" type="number" placeholder="123">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-sm btn-success float-right">
                        <i class="mdi mdi-gamepad-circle"></i> <a href = <%= update_subscription_payment_venue_owner_payments_path%> >Continue</a></button>
                   
                </div>
            </div>
        </div>
    </div>
</div>