config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'landing#index' # ite means url '/'

  # get 'pages/home'

  devise_for :users, :controllers => { :sessions => "users/sessions" ,:registrations => "users/registrations" }
  
  # All Customer Routes
  namespace :customers do
    resources :venues, only: [:index, :show]
    resources :bookings, except: [:new] do
      # collection means we do not need any booking id 
      # while its opposite is member keywork which required id and add it to URL 
      collection do
        get 'venues/:venue_id' => 'bookings#new', as: :new #
        post '/search' , to: 'venues#search_venue', as: :search_venue
      end
    end
  end
  # all venue_Owner routes
  namespace :venue_owner do
    resources :payments  do 
      collection do
         get :get_subscription_payment
         get :update_subscription_payment
      end
    end
    resources :venues 
    resources :bookings do
      member do 
        get :approve
      end
    end

   end
   
  # subscription
  resources :subscription
    get "/subscription/create/:subscription_type" => "subscription#create_subscription"

end



  # get 'landing/index'
# Landing route
  # resources :landing

  #  Customer route
  # login
  # get "/home/login" => "home#login"
  # get "/venue_owner/:id" => "venue_owner#update_subscription"
  
  # post "/saveVO" => "venue_owner#create" 
          # create_booking
  # get "/booking/index" => "booking#index"
  # get  "/booking/new" => "booking#new"
  # post  "/booking" => "booking#create"
  
  # venue route
  
  # post "/venues" => "venues#destroy"

  # get "/venue/" => "venue#index"
  # get "/venue/new" =>  "venue#new"
  # post "venue_create" => "venue#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/venue.rb
class Venue < ApplicationRecord
    has_many :bookings
    belongs_to :user
end

app/controllers/customers/bookings_controller.rb
class Customers::BookingsController < ApplicationController
    layout "landing"
    
    before_action :authenticate_user!

    def index
        @bookings = Booking.where(user_id: current_user.id)
    end
     
    def new
        #Find Venue to create Booking
        @venue = Venue.find_by_id(params[:venue_id])
        @booking = Booking.new #
    end

    # def show
    #     debugger
    #     @booking = Booking.find_by_id(params[:booking_id])
    # end

    def create
        debugger  
        @venue = Venue.find_by_id(booking_params[:venue_id])
        @booking = Booking.new(booking_params)  
        @booking.user_id = current_user.id
        if @booking.save!
            BookingMailer.with(booking: @booking, venue: @venue).new_booking_email.deliver_later
            flash[:success] = "Thank you for your booking! We'll get contact you soon!"
            redirect_to customers_bookings_path(@booking), notice: 'booking was successfully updated.'   
        else
          flash[:alert] = "Your account has expired! please contact admin."
          redirect_to customers_bookings_path(@booking), notice: 'booking was successfully updated.'   
        end 
        # debugger    
        # @booking = Booking.new(booking_params)  
        # @booking.user_id = current_user.id
        # if @booking.save!
        # end 

        # # booking mailer section
        # @venue = Venue.find_by_id(booking_params[:venue_id])
        # @booking = Booking.new(booking_params)
        # if @booking.save
          
        #   BookingMailer.with(booking: @booking, venue: @venue).new_booking_email.deliver_now
        #   flash[:success] = "Thank you for your booking! We'll get contact you soon!"
        #   redirect_to customers_booking_path
        # else
        #   flash.now[:error] = "Your order form had some errors. Please check the form and resubmit."
        #   render :new
        # end

              

    end 

    def destroy
      # debugger
        @booking = Booking.find(params[:id])
        @booking.destroy
        respond_to do |format|
        format.html { redirect_to customers_bookings_path, notice: 'booking was successfully destroyed.' }
        # format.json { head :no_content }
      end
    end

    # these are called strong params which is security features which allows
#  only specific keys to be accepted from the web page
    private 
    def booking_params
        #Strong Params
        params.require(:booking).permit(:name,:reservation_details, :location, :group, :date, :venue_id)
    end
    
end

app/controllers/customers/venues_controller.rb
class Customers::VenuesController < ApplicationController
    
  protect_from_forgery
  layout "landing"
    
  def index
      @venues = Venue.all 
      
  end

  def show
      @venues = Venue.all
  end

  def search_venue
    @venues = Venue.where('name LIKE ?', "%#{params[:search]}%")
    render :index    
  end

end

app/controllers/venue_owner/venues_controller.rb
class VenueOwner::VenuesController < ApplicationController

  protect_from_forgery

    layout "landing"
   
  def index
      # @venue = current_user.venues
      # Both Lines are working similar
      @venue = Venue.where(user_id: current_user.id)  
      # PaymentMailer.with( venue: @venue, user: current_user).payment_paid_email.deliver_now
  end

  def new 
      @venue = Venue.new
  end 

  def show
      @venue = Venue.find_by_id(params[:id])
    # debugger
  end

  def edit
        @venue = Venue.find(params[:id])       
  end

  def update
    debugger    
      @venue = Venue.find(params[:id])
      if @venue.update(venue_params)
          redirect_to venue_owner_venues_path, notice: 'Venue was successfully updated.'        
      end
  end

  def create
      @current_user_venues = Venue.where(user_id: current_user.id)
     debugger
    #  Check what is the subscription limit of venue owner and then check if 
    #  he can make a new venue or not.
      if ((current_user.subscription  == 'basic' && @current_user_venues.count  == 2)  || (current_user.subscription  == 'pro' && @current_user_venues.count  == 5))

        redirect_to venue_owner_venues_path, notice: "Please upgrade your subscripton to create new venues" 
      else
        @venue = Venue.new(venue_params)
        @venue.user_id = current_user.id
        @venue.save
        redirect_to venue_owner_venues_path
      end
    end
  
  def destroy
      @venue = Venue.find(params[:id])
      debugger
      @venue.destroy! 
      respond_to do |format|
          format.html { redirect_to venue_owner_venues_url, notice: 'Venue was successfully destroyed.' }
          format.json { head :no_content }
       end
    end

# these are called strong params which is security features which allows
#  only specific keys to be accepted from the web page
  private 
  def venue_params
      params.require(:venue).permit(:name,:address,:venue_type,:price, :contact_no,)
  end
    
end

app/helpers/venue_owner/venues_helper.rb
module VenueOwner::VenuesHelper
end

app/views/customers/venues/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title -->
    <title>corporative event affairs</title>
    <!-- Favicon -->
    <link rel="assets" href="/img/core-img/favicon.ico">
    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="/assets/booking/style.css">
</head>

<body>
 <!-- ##### Header Area Start ##### -->
    <header class="header-area">
        <!-- Navbar Area -->
        <div class="palatin-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="palatinNav">

                        <!-- Nav brand -->
                        <%# <a href="index.html" class="btn palatin-btn">Corperative Event Affairs </a> %>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                            <div class = "classy-menu" >
                              <!-- Nav Start -->
                             <div class="classynav" >
                               <!-- Search form -->
                               <form method ="post" action='/customers/bookings/search'  class="form-inline d-flex justify-content-center md-form form-sm active-cyan-2 mt-2">
                                 <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search"
                                 aria-label="Search" name="search">
                                </form>                           
                             </div>   
                            </div>
                              <a href=<%= customers_bookings_path(@booking)%> class="btn palatin-btn">see bookings</a>
                            <!-- Nav End -->
                         </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <section class="rooms-area section-padding-100-0">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-6">
                    <div class="section-heading text-center ">
                        <h2>Choose a Venue</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris
                            sceleri sque, at rutrum nulla dictum. Ut ac ligula sapien.</p>
                    </div>
                </div>       
            </div>

            <div class="row justify-content-center">
               <% @venues.each_with_index do |v|%> 
                 <!-- Mariage Palace Area -->
                 <%if v.venue_type == "Hotel"%>
                     <div class="col-12 col-md-6 col-lg-4">
							<div class="single-rooms-area wow fadeInUp" data-wow-delay="500ms">
                                <!-- Thumbnail -->
                                <div class="bg-thumbnail bg-img" style="background-image: url(/assets/bg-img/17.jpg);"></div>
                                <!-- Price -->
                                <p class="price-from">From $50/person</p>
                                <div class="rooms-text">
                                        <div class="line"></div>
                                        <h4><%= v.name%></h4>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus
                                                mauris sceleri sque.</p>
                                </div>
                                <!-- Registerd Mariage Palace -->
                                <a href= <%= new_customers_bookings_path(venue_id: v.id)%> class="book-room-btn btn palatin-btn">Book Now</a>
							 </div>
					 </div>

                   <%elsif v.venue_type == "Mariage Palace"%>
                   <div class="col-12 col-md-6 col-lg-4">
                        <div class="single-rooms-area wow fadeInUp" data-wow-delay="500ms">
                            <!-- Thumbnail -->
                            <div class="bg-thumbnail bg-img" style="background-image: url(/assets/bg-img/42.jpg);"></div>
                            <!-- Price -->
                            <p class="price-from">From $70/person</p>
                            <div class="rooms-text">
                                    <div class="line"></div>
                                    <h4><%= v.name%></h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus
                                            mauris sceleri sque.</p>
                            </div>
                            <!-- Registerd Mariage Palace -->
                            <a href= <%= new_customers_bookings_path(venue_id: v.id)%> class="book-room-btn btn palatin-btn">Book Now</a>
                        </div>
					 </div>
                     
					 <%else v.venue_type == "Resturant"%>
                        <div class="col-12 col-md-6 col-lg-4">
                            <div class="single-rooms-area wow fadeInUp" data-wow-delay="500ms">
                                    <!-- Thumbnail -->
                                    <div class="bg-thumbnail bg-img" style="background-image: url(/assets/bg-img/36.jpg);"></div>
                                    <!-- Price -->
                                    <p class="price-from">From $40/person</p>
                                    <div class="rooms-text">
                                            <div class="line"></div>
                                            <h4><%= v.name%></h4>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus
                                                    mauris sceleri sque.</p>
                                    </div>
                                    <!-- Registerd resturants -->
                                    <a href= <%= new_customers_bookings_path(venue_id: v.id)%> class="book-room-btn btn palatin-btn">Book Now</a>
                                </div>
							</div>
                  <%end%>   
                <%end%>
            </div>
        </div>
    </section>
    <!-- ##### Footer Area Start ##### -->
    <footer class="footer-area">
        <div class="container">
            <div class="row">

                <!-- Footer Widget Area -->
                <div class="col-12 col-lg-5">
                    <div class="footer-widget-area mt-50">
                        <a href="#" class="d-block mb-5"><img src="/assets/core-img/logo.png" alt=""></a>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris
                            sceleri sque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus
                            finibus. </p>
                    </div>
                </div>

                
                <!-- Footer Widget Area -->
                <div class="col-12 col-md-6 col-lg-3">
                    <div class="footer-widget-area mt-50">
                        <h6 class="widget-title mb-5">Subscribe to our newsletter</h6>
                        <form action="#" method="post" class="subscribe-form">
                            <input type="email" name="subscribe-email" id="subscribeemail" placeholder="Your E-mail">
                            <button type="submit">Subscribe</button>
                        </form>
                    </div>
                </div>
            
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="/assets/js/booking_js/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="/assets/js/booking_js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="/assets/js/booking_js/bootstrap.min.js"></script>
    <!-- All Plugins js -->
    <script src="/assets/js/booking_js/plugins.js"></script>
    <!-- Active js -->
    <script src="/assets/js/booking_js/active.js"></script>
</body>

</html>