config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'landing#index' # ite means url '/'

  # get 'pages/home'

  devise_for :users, :controllers => { :sessions => "users/sessions" ,:registrations => "users/registrations" }
  
  # All Customer Routes
  namespace :customers do
    resources :venues, only: [:index, :show]
    resources :bookings, except: [:new] do
      # collection means we do not need any booking id 
      # while its opposite is member keywork which required id and add it to URL 
      collection do
        get 'venues/:venue_id' => 'bookings#new', as: :new #
        post '/search' , to: 'venues#search_venue', as: :search_venue
      end
    end
  end
  # all venue_Owner routes
  namespace :venue_owner do
    resources :payments  do 
      collection do
         get :get_subscription_payment
         get :update_subscription_payment
      end
    end
    resources :venues 
    resources :bookings do
      member do 
        get :approve
      end
    end

   end
   
  # subscription
  resources :subscription
    get "/subscription/create/:subscription_type" => "subscription#create_subscription"

end



  # get 'landing/index'
# Landing route
  # resources :landing

  #  Customer route
  # login
  # get "/home/login" => "home#login"
  # get "/venue_owner/:id" => "venue_owner#update_subscription"
  
  # post "/saveVO" => "venue_owner#create" 
          # create_booking
  # get "/booking/index" => "booking#index"
  # get  "/booking/new" => "booking#new"
  # post  "/booking" => "booking#create"
  
  # venue route
  
  # post "/venues" => "venues#destroy"

  # get "/venue/" => "venue#index"
  # get "/venue/new" =>  "venue#new"
  # post "venue_create" => "venue#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/venue.rb
class Venue < ApplicationRecord
    has_many :bookings
    belongs_to :user
end

app/controllers/customers/venues_controller.rb
class Customers::VenuesController < ApplicationController
    
  protect_from_forgery
  layout "landing"
    
  def index
      @venues = Venue.all 
      
  end

  def show
      @venues = Venue.all
  end

  def search_venue
    @venues = Venue.where('name LIKE ?', "%#{params[:search]}%")
    render :index    
  end

end

app/controllers/venue_owner/venues_controller.rb
class VenueOwner::VenuesController < ApplicationController

  protect_from_forgery

    layout "landing"
   
  def index
      # @venue = current_user.venues
      # Both Lines are working similar
      @venue = Venue.where(user_id: current_user.id)  
      # PaymentMailer.with( venue: @venue, user: current_user).payment_paid_email.deliver_now
  end

  def new 
      @venue = Venue.new
  end 

  def show
      @venue = Venue.find_by_id(params[:id])
    # debugger
  end

  def edit
        @venue = Venue.find(params[:id])       
  end

  def update
    debugger    
      @venue = Venue.find(params[:id])
      if @venue.update(venue_params)
          redirect_to venue_owner_venues_path, notice: 'Venue was successfully updated.'        
      end
  end

  def create
      @current_user_venues = Venue.where(user_id: current_user.id)
     debugger
    #  Check what is the subscription limit of venue owner and then check if 
    #  he can make a new venue or not.
      if ((current_user.subscription  == 'basic' && @current_user_venues.count  == 2)  || (current_user.subscription  == 'pro' && @current_user_venues.count  == 5))

        redirect_to venue_owner_venues_path, notice: "Please upgrade your subscripton to create new venues" 
      else
        @venue = Venue.new(venue_params)
        @venue.user_id = current_user.id
        @venue.save
        redirect_to venue_owner_venues_path
      end
    end
  
  def destroy
      @venue = Venue.find(params[:id])
      debugger
      @venue.destroy! 
      respond_to do |format|
          format.html { redirect_to venue_owner_venues_url, notice: 'Venue was successfully destroyed.' }
          format.json { head :no_content }
       end
    end

# these are called strong params which is security features which allows
#  only specific keys to be accepted from the web page
  private 
  def venue_params
      params.require(:venue).permit(:name,:address,:venue_type,:price, :contact_no,)
  end
    
end

app/helpers/venue_owner/venues_helper.rb
module VenueOwner::VenuesHelper
end

app/views/venues/index.html.erb
<div class="page-header" data-parallax="true" style="background-image: url('https://wonderfulengineering.');">
 <div class="container">
   <%= render "/layouts/landing"%>
   <div class="row">
     <div class="col-10">
       <h2 style="margin: 0;">venues</h2>
     </div>
     <div class="col-12">
       <a class="btn btn-success float-right btn-sm margin-top = 35px" href="/venues/new"> Create_venue </a>
     </div>
   </div>
    <div  style = "position:relative; height:400px; overflow:auto; display:block;">
      <table class="table table-bordered table-striped md-0 table-hover table-dark">
       <thead>
         <tr>
           <th>#</th>
           <th>name</th> 
           <th>address</th>
           <th>venue_type</th>
           <th>contact_no</th>
           <th> action</th>
          </tr>
       </thead>
       <tbody >
         <% @venue.each_with_index do |q|%> 
           <tr>
             <td><%= q.id%></td>
             <td><%= q.name%></td>
             <td><%= q.address%></td>
             <td><%= q.venue_type%></td>
             <td><%= q.contact_no%></td>
             <td style="padding: 0px;"  ><a class="btn btn-success float-right btn-sm"  href="/venues/<%= q.id%>"> view </a></td>
             <td style="padding:0px;"><a class="btn btn-success float-right btn-sm" href="/venues/<%= q.id%>/edit"> Edit </a></td>
             <td><%= link_to 'destroy', venue_path(q), method: :delete, data: { confirm: 'Are you sure?' }%> </td>
           </tr>
         <%end%>   
       </tbody>
      </table>
    </div>
  </div>
</div>