config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'landing#index' # ite means url '/'

  # get 'pages/home'

  devise_for :users, :controllers => { :sessions => "users/sessions" ,:registrations => "users/registrations" }
  
  # All Customer Routes
  namespace :customers do
    resources :venues, only: [:index, :show]
    resources :bookings, except: [:new] do
      # collection means we do not need any booking id 
      # while its opposite is member keywork which required id and add it to URL 
      collection do
        get 'venues/:venue_id' => 'bookings#new', as: :new #
        post '/search' , to: 'venues#search_venue', as: :search_venue
      end
    end
  end
  # all venue_Owner routes
  namespace :venue_owner do
    resources :payments  do 
      collection do
         get :get_subscription_payment
         get :update_subscription_payment
      end
    end
    resources :venues 
    resources :bookings do
      member do 
        get :approve
      end
    end

   end
   
  # subscription
  resources :subscription
    get "/subscription/create/:subscription_type" => "subscription#create_subscription"

end



  # get 'landing/index'
# Landing route
  # resources :landing

  #  Customer route
  # login
  # get "/home/login" => "home#login"
  # get "/venue_owner/:id" => "venue_owner#update_subscription"
  
  # post "/saveVO" => "venue_owner#create" 
          # create_booking
  # get "/booking/index" => "booking#index"
  # get  "/booking/new" => "booking#new"
  # post  "/booking" => "booking#create"
  
  # venue route
  
  # post "/venues" => "venues#destroy"

  # get "/venue/" => "venue#index"
  # get "/venue/new" =>  "venue#new"
  # post "venue_create" => "venue#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :user
    belongs_to :venue

    # before_create :check_booking

    # def check_booking 
    #   case current_user.subscription
    #   when "basic"
    #     return false if current_user.bookings.length == 5
    #   when "pro"
    #     return false if current_user.bookings.length == 20
    #   default 
    #     return true
    #   end
      
    # end
  end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :User

end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          
  # Validation
  # validates :first_name , presence: :true
  # validates :last_name , presence: :true
  has_many :venues
  has_many :payments
  # has_many :venues, class_name: 'Venue', foreign_key: 'venue_owner_id'
  enum subscription: {basic: "basic", pro: "pro", enterprise: "enterprise"}
  
  def name
    return self.first_name + " " + self.last_name rescue nil
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
    has_many :bookings
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  # def after_sign_in_path_for(resource)
  #   # debugger
  #   if resource.role == "venue_owner"
  #    "/landing" 
  #   else
  #     super
  #   end
  # end
  protected
    def  configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name,:last_name,:role, :email, :password)}

      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
    end
end

app/controllers/customers/venues_controller.rb
class Customers::VenuesController < ApplicationController
    
  protect_from_forgery
  layout "landing"
    
  def index
      @venues = Venue.all 
      
  end

  def show
      @venues = Venue.all
  end

  def search_venue
    @venues = Venue.where('name LIKE ?', "%#{params[:search]}%")
    render :index    
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

    layout "landing"

    def index
             
    end
    def show
        @booking = Booking.all

    end
    
end

app/controllers/subscription_controller.rb
class SubscriptionController < ApplicationController

    def create_subscription
        debugger
            current_user.update(subscription: params[:subscription_type])
            redirect_to venue_owner_venue_payment_path
    end
     
    

 end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
 
  layout "landing"

  # GET /resource/password/new  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
 
  # before_action :configure_sign_in_params, only: [:create]
  
  layout "landing"
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end 

  private
  def after_sign_in_path_for(resources)
    if @user.role == 'venue_owner'
     venue_owner_venues_path    
    else 
      customers_venues_path  
    end
    
  end
  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/venue_owner/venues_helper.rb
module VenueOwner::VenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/subscription/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/subscription/pricing-plan.css">
</head>

<body>
  <main>
    <div class="container">
      <h5 class="text-center pricing-table-subtitle">SUBSCRIPTION PLAN</h5>
      <h1 class="text-center pricing-table-title">Pricing Table</h1>
      <div class="row">
            <% Subscription.all.each do |s|%>
             <div class="col-md-4">
                    <div class="card pricing-card pricing-plan-basic">
                    <div class="card-body">
                      <i class="mdi mdi-cube-outline pricing-plan-icon"></i>
                      <p class="pricing-plan-title"><%= s.name%></p>
                      <p class="pricing-plan-title"><%= s.price%> </p>
                      <ul class="pricing-plan-features"><%= s.sub_details%>
                        <%# <li>Only 5 Venues at once(per week)</li> %>
                      </ul>
                      <a href = <%= get_subscription_payment_venue_owner_payments_path(subscription: s.name)%> class="btn pricing-plan-purchase-btn"><%= s.name %></a>
                      <%# <button  type="submit" class="btn pricing-plan-purchase-btn">Free</button> %>
                   </div>
                 </div>
                <%# <% end %> 
             </div>
                  <%end%>

             
            <%# <div class="col-md-4">
              <div class="card pricing-card pricing-plan-enterprise">
                <div class="card-body">
                  <i class="mdi mdi-wallet-giftcard pricing-plan-icon"></i>
                  <p class="pricing-plan-title">Enterprise</p>
                  <h3 class="pricing-plan-cost ml-auto">$69</h3>
                  <ul class="pricing-plan-features">
                    <li>Unlimited conferences</li>
                    <li>100 participants max</li>
                    <li>Custom Hold Music</li>
                    <li>10 participants max</li>
                  </ul>
                  <a href="/subscription/create/enterprise" class="btn pricing-plan-purchase-btn">Enterprise</a>
                </div>
              </div>
            </div> %>
      </div>
    </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>
</html>